---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-healthcheck
rules:
- nonResourceURLs:
  - /healthz
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-healthcheck
roleRef:
  kind: ClusterRole
  name: haproxy-healthcheck
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: haproxy
  apiGroup: rbac.authorization.k8s.io
